name: 'Download Tar Artifact'
description: 'Download and extract a tar artifact that was previously uploaded in the workflow by the upload-tartifact action'

inputs:
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@main
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - run: tar -xvf artifact.tar
      working-directory: ${{ inputs.path }}
      shell: 'bash'

    - run: ls -alR
      working-directory: ${{ inputs.path }}
      shell: 'bash'

    - run: rm artifact.tar
      working-directory: ${{ inputs.path }}
      shell: 'bash'
